/* SQL Que crea todas las tablas del proyecto*/

--Operador
CREATE TABLE Operador (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Nombre varchar(50),
    Direccion varchar(50),
    DType varchar(10)
    );

--Hostal
CREATE TABLE Hostal (
    Id INTEGER, --fk Operador
	Apertura number, 
	Cierre number, 
    Desayuno number
	);

/*Hotel*/
CREATE TABLE Hotel (
    Id INTEGER, --fk Operador
	Desayuno number,
	Restaurante number,
	Piscina number,
	parqueadero number,
	horario number
	);

/*ViviendaU*/
CREATE TABLE ViviendaU (
    Id INTEGER --FK Operador
	);
    
--Alojamiento
CREATE TABLE Alojamiento (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    precio number,
    capacidad number,
    DType varchar(10)
    );

--HostalRoom
CREATE TABLE HostalRoom (
    Id INTEGER, --fk Alojamiento
	Cuarto number,
	IDHOSTAL INTEGER -- fk hostal
	);
	
--HotelRoom
CREATE TABLE HotelRoom (
    Id INTEGER, --FK Alojamiento
    Tipo varchar(10),
	Cuarto number,
	Banera number,
	Jacuzzi number,
	Sala number,
	Cocina number,
	Cable number
	IDHOTEL INTEGER -- fk hotel
	);

--ViviendaURoom
CREATE TABLE ViviendaRoom (
    Id INTEGER, --fk Alojamiento
	Cuarto number,
	Compartida float,
	Restaurante float,
	SalaDeEstudio float,
	SalaEsparcimiento float,
	Gym float,
	Precio float,
	IDVIVIENDA INTEGER --fk vivienda
	);
	
--Inmueble
CREATE TABLE Inmueble (
    Id INTEGER, --fk alojamiento
	Amoblado number,
	Servicios number,
	Cable number,
	Administracion number,  
	Direccion varchar(50),
	Dueno VARCHAR(30) --fk cliente
	);
	
--VecinoRoom
CREATE TABLE VecinoRoom (
    ID INTEGER, --FK ALOJAMIENTO
	Habitaciones number,
	Banos number,
	Direccion varchar(50),
	Menaje varchar(140),
	Dueno VARCHAR(30) --FK Vecino.Cedula
	);
	
  
--Persona
CREATE TABLE Persona (
    Cedula varchar(30),
    Nombre varchar(50),
    Rol varchar(10),
    fechaNacimiento TIMESTAMP
    );
--Usuario
CREATE TABLE Cliente (
	cedula varchar(30) --fk persona
    );
	
--Vecino
CREATE TABLE Vecino (
	Cedula varchar(30) --fk persona
	);
    
--Rserva
CREATE TABLE RESERVA (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FechaInicio TIMESTAMP,
	FechaFin TIMESTAMP,
    Precio number,
    Cedula varchar(30), --Fk al cliente
    Cuarto Integer --Fk al cuarto
    );    
    
CREATE TABLE RESERVASMASIVAS(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CANTIDAD INTEGER,
    DESCRIPCION VARCHAR (140),
    FechaInicio TIMESTAMP,
    FECHAFIN TIMESTAMP,
    Cedula varchar(30)--fk cliente
    );

