--BORRA TODAS LAS TABLAS DEL PROYECTO!!!!!!!!!!!!!!!!
DROP TABLE RESERVASMASIVAS;

DROP TABLE VECINOROOM;

DROP TABLE VIVIENDAROOM;

DROP TABLE INMUEBLE;
DROP TABLE HOSTALROOM;
DROP TABLE HOTELROOM;
DROP TABLE CLIENTE;
DROP TABLE VECINO;
DROP TABLE VIVIENDAU;
DROP TABLE HOTEL;
DROP TABLE HOSTAL;
DROP TABLE RESERVA;
DROP TABLE ALOJAMIENTO;
DROP TABLE OPERADOR;
DROP TABLE PERSONA;
